<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>KEngine</AssemblyName>
    <RootNamespace>KEngine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Components/Transform.cs" />
  </ItemGroup>

</Project>
